name: "Deploy Web Build"
on:
  push:
    branches:
      - main  # 或者是你的主分支名

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web      # 核心：指定部署 web 文件夹下的内容
          branch: gh-pages # 部署到这个分支
